language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="dolmen:. dolmen_lsp:. dolmen_bin:. dolmen_loop:. dolmen_type:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="dolmen" CAML_VERSION="4.03"
  - PACKAGE="dolmen" CAML_VERSION="4.04"
  - PACKAGE="dolmen" CAML_VERSION="4.05"
  - PACKAGE="dolmen" CAML_VERSION="4.06"
  - PACKAGE="dolmen" CAML_VERSION="4.08"
  - PACKAGE="dolmen" CAML_VERSION="4.09"
  - PACKAGE="dolmen_lsp" CAML_VERSION="4.06"
  - PACKAGE="dolmen_lsp" CAML_VERSION="4.08"
